"""initial

Revision ID: 8d3af6a0cb08
Revises:
Create Date: 2025-09-12 15:02:55.108839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d3af6a0cb08"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lansweeper_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.INTEGER(), nullable=False),
        sa.Column("host_type", sa.TEXT, default="Unknown"),
        sa.Column("typename", sa.VARCHAR(), nullable=True),
        sa.Column("operating_system", sa.TEXT(), nullable=True),
        sa.Column("ou", sa.TEXT(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("ip_address", sa.VARCHAR(), nullable=True),
        sa.Column("mac", sa.VARCHAR(), nullable=True),
        sa.Column("processor", sa.VARCHAR(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("manufacturer", sa.TEXT(), nullable=True),
        sa.Column("model", sa.TEXT(), nullable=True),
        sa.Column("serial_number", sa.TEXT(), nullable=True),
        sa.Column("detected", sa.BOOLEAN(), nullable=True),
        sa.Column("custom_fields", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="integration_modules",
        if_not_exists=True,
    )
    op.create_table(
        "sync_states",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("service_name", sa.TEXT(), nullable=False),
        sa.Column("table_name", sa.TEXT(), nullable=False),
        sa.Column("result", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
        schema="integration_modules",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_states", schema="integration_modules")
    op.drop_table("lansweeper_data", schema="integration_modules")
    # ### end Alembic commands ###
